FROM python:3.6.5

WORKDIR /code 

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

EXPOSE 8000

COPY . .

CMD ["python3", "manage.py", "runserver", "localhost:8000"]
